### ISSUE TITLE
What VPNs have been tested? 

### ISSUE THREAD

**Issue by rbeldin** [libcthorne/samlwebcookie#2]
Hi... 

Just curious since we interact with a Pulse VPN.  I see that the code has some bits that reference Azure.   Any tips on debugging this as I experiment?  

Thanks, 

Rick

**Comment by libcthorne** [comment]
Hi Rick,

This has only been tested against an Azure MFA server so far. I'd be interested to know if it's compatible with Pulse VPN.

You'll need to work out what to put in the following variables to use the script: 
```
SAML_HOST=saml.host.my.company
FS_AUTH_HOST=auth.host.my.company
VPN_HOST=the.vpn.my.company
VPN_USERNAME=my.username@my.company
```

I would start by monitoring the traffic that gets sent when you connect to your VPN using a standard VPN client. You can use something like Wireshark (or your browser's Network tab if applicable) to do this. You'll want to look for domain names containing "saml", "fs.auth" or "vpn" - if they are present then it's likely you'll be able to use `samlwebcookie`.

**Comment by jschwartzenberg** [comment]
Is one of the hosts one from Microsoft when using Azure MFA? I'm getting this now:
```
Running samlwebcookie
Traceback (most recent call last):
  File "/samlwebcookie/webcookie.py", line 58, in <module>
    url=r.headers['Location'],
  File "/usr/local/lib/python3.8/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```

Does that mean I might have the wrong hosts filled in?

**Comment by jangrewe** [comment]
My `.env` looks like this:
```
SAML_HOST=login.microsoftonline.com
FS_AUTH_HOST=<ourcompany>.onmicrosoft.com
VPN_HOST=remote.<ourcompany>.com
VPN_USERNAME=me@<ourcompany>.com
```
and i get the same error.

**Comment by libcthorne** [comment]
All the URLs are internal in my case:
```
SAML_HOST="vpn.company.org"
FS_AUTH_HOST="fs.auth.company.org"
VPN_HOST="vpn.company.org" 
```
