### ISSUE TITLE
why the requirement for docker?

### ISSUE THREAD

**Issue by bryanerank** [libcthorne/samlwebcookie#3]
Hi, Sorry for filing this as a bug, but I'm not certain of the best way to ask this question.  I'm also kinda old, so don't get off the bat why docker is needed here.  My best guess is that it provides the means to normalize the runtime env for the connect script?

Anyhow, I'd like to use the connect.sh script locally to connect a Pi 3b+ to a GP VPN.  And would prefer not to require docker.  Can I just exec the docker -run command in a local environment and pass the return to openconnect?

Thanks for your work and tolerance for noobs asking noobie stuff.

Bryan

**Comment by libcthorne** [comment]
Hi @bryanerank , Docker was added to simplify the setup process, but you can also just run `pip install -r requirements.txt` and use something like the following one-liner:
```
sudo openconnect -v vpn.yourcompany.org --cookie="$(SAML_HOST="vpn.yourcompany.org" FS_AUTH_HOST="fs.auth.yourcompany.org" VPN_HOST="vpn.yourcompany.org" VPN_USERNAME="jon.snow@yourcompany.org" VPN_PASSWORD="$(cat ~/.vpn)" python -u ~/samlwebcookie/webcookie.py | tee /dev/tty | tail -1)"
```
The first thing to check would be if the script is compatible with your target VPN and running the following (with environment variables substituted as needed) should tell you:
```
SAML_HOST="vpn.yourcompany.org" FS_AUTH_HOST="fs.auth.yourcompany.org" VPN_HOST="vpn.yourcompany.org" VPN_USERNAME="jon.snow@yourcompany.org" VPN_PASSWORD="$(cat ~/.vpn)" python -u ~/samlwebcookie/webcookie.py
```

**Comment by bryanerank** [comment]
Sweet, I'll give it a shot. Thanks! :)
